Module = "hoper"
# dev | test | prod
Env = "dev"

[dev]
Debug = true
ConfigTemplateDir = "."
NoInject = []
[dev.localConfig]
Paths = ["local.toml"]

[dev.configCenter]
Type = "local"
NoInject = ["Apollo", "Etcd", "Es"]
Format = 'toml'

[dev.configCenter.http]
Interval = 100
Url = "http://localhost:6666/local.toml"

[test]

[test.configCenter]
configType = "nacos"
Watch = true
NoInject = ["Apollo", "Etcd", "Es"]

[test.configCenter.nacos]
DataId = "pro"
Group = "DEFAULT_GROUP"

[[test.configCenter.nacos.ServerConfigs]]
Scheme = "http"
IpAddr = "localhost"
Port = 9000
GrpcPort = 10000

[test.configCenter.nacos.ClientConfig]
NamespaceId = ""
username = "nacos"
password = "123456"
LogLevel = "debug"

[prod]
