FROM jybl/timezone AS tz

# Builder Image
FROM jybl/protogen AS compile

ENV GOPROXY=https://goproxy.io,https://goproxy.cn,direct

WORKDIR /build

ADD . /build

RUN --mount=type=cache,id=gobuild,target=/root/.cache/go-build \
    --mount=type=cache,id=gopath,target=/go \
    go build -trimpath -o  /build/${output} /build/${sourceFile}

# Runtime Image
FROM frolvlad/alpine-glibc

#修改容器时区
ARG TZ=Asia/Shanghai
ENV TZ=${TZ} LANG=C.UTF-8
COPY --from=tz /usr/share/zoneinfo/$TZ /usr/share/zoneinfo/$TZ
RUN echo $TZ > /etc/timezone && ln -s /usr/share/zoneinfo/$TZ /etc/localtime

WORKDIR /app

COPY --from=compile /work/${output} /app

CMD ["${cmd}"]
