FROM jybl/timezone AS tz
FROM node:22-alpine3.16 AS base
#修改容器时区
ARG TZ=Asia/Shanghai
ENV TZ=${TZ} LANG=C.UTF-8
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
COPY --from=tz /usr/share/zoneinfo/$TZ /usr/share/zoneinfo/$TZ
RUN echo $TZ > /etc/timezone && ln -s /usr/share/zoneinfo/$TZ /etc/localtime
RUN corepack enable

WORKDIR /app
ADD . /app


FROM base AS prod-deps
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --prod --frozen-lockfile

FROM base AS build
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm run build

FROM base
COPY --from=prod-deps /app/node_modules /app/node_modules
COPY --from=build /app/dist /app/dist

CMD [ "pnpm", "start" ]

#RUN pnpm install -g nodemon
#CMD ["nodemon", "${cmd}"]