// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Sample

type Equipment = byte
const (
	EquipmentNONE Equipment = 0
	EquipmentWeapon Equipment = 1
)

var EnumNamesEquipment = map[Equipment]string{
	EquipmentNONE:"NONE",
	EquipmentWeapon:"Weapon",
}

