name: app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter_localizations:
    sdk: flutter

  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  async: ^2.12.0
  http: ^1.4.0
  dio: ^5.8.0+1
  webview_flutter: ^4.11.0
  #webview_flutter_web: ^0.2.2+4
  ffi: ^2.1.4
  json_annotation: ^4.9.0
  flutter_markdown: ^0.7.7+1
  sqflite: ^2.4.2
  #sqflite_common_ffi_web: ^0.4.3+1
  drift: ^2.26.1
  hive_ce: ^2.11.2
  flutter_cache_manager: ^3.4.1
  shared_preferences: ^2.5.3
  get: ^4.7.2
  flutter_local_notifications: ^19.2.1
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  geolocator: ^14.0.0
  protobuf: ^4.0.0
  grpc: ^4.0.4
  carousel_slider: ^5.0.0
  fl_chart: ^1.0.0
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  #flutter_swiper: ^1.1.6
  introduction_screen: ^3.1.17
  #image: ^3.0.2
  #photo_view: ^0.12.0
  #cached_network_image: ^3.1.0
  extended_text: ^15.0.2
  extended_text_field: ^16.0.2
  animated_text_kit: ^4.2.3
  auto_size_text: ^3.0.0
  syncfusion_flutter_charts: ^29.2.5
  camera: ^0.11.1
  qr_flutter: ^4.1.0
  image_picker: ^1.1.2
  file_picker: ^10.1.2
  video_player: ^2.9.5
  just_audio: ^0.10.3
  extended_image: ^10.0.1
  animations: ^2.0.11
  intl: ^0.20.2
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  permission_handler: ^12.0.0+1
  args: ^2.4.2
  animate_do: ^4.2.0
  getwidget: ^6.0.0
  fluttertoast: ^8.2.12
  vector_math: ^2.2.0
  shelf_proxy: ^1.0.4
  feedback: ^3.0.1
  flex_color_scheme: ^8.2.0
  equatable: ^2.0.5
  logging: ^1.3.0
  flutter_slidable: ^4.0.0
  package_info_plus: ^8.3.0
  device_info_plus: ^11.4.0
  connectivity_plus: ^6.1.4
  share_plus: ^11.0.0
  infinite_scroll_pagination: ^5.0.0
  convex_bottom_bar: ^3.2.0
  logger: ^2.5.0
  sqlite3_flutter_libs: ^0.5.33
  applib:
    path: ../../../hoper/thirdparty/applib
 # flame: ^1.7.1 游戏引擎
# provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: ^2.3.5
  pigeon: ^25.3.2
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  protoc_plugin: ^22.2.0
  dart_style: ^3.1.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3
  freezed: ^3.0.6
  flutter_lints: ^5.0.0

dependency_overrides: {
  vector_math: ^2.2.0
}

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/weather/
    - assets/splash/splash.jpg
    - assets/dist/
    - assets/dist/assets/
    - assets/js/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.jpg"
    background_color: "#0175C2"
    theme_color: "#0175C2"
  windows:
    generate: true
    image_path: "assets/icon/icon.jpg"
    icon_size: 48 # min:48, max:256, default: 48