Module = "hoper"
# dev | test | prod
Env = "dev"

[dev]
Debug = true
ConfigTemplateDir = "./config"
NoInject = ["Apollo", "Etcd", "Es"]
[dev.localConfig]
Paths = ["config/local.toml"]


[dev.configCenter.http]
Interval = 100
Url = "http://localhost:6666/local.toml"

[test]
NoInject = ["Apollo", "Etcd", "Es"]

[test.configCenter]
Format = 'toml'
Type = "nacos"

[test.configCenter.nacos]
DataId = "pro"
Group = "DEFAULT_GROUP"

[[test.configCenter.nacos.ServerConfigs]]
Scheme = "http"
IpAddr = "localhost"
Port = 9000
GrpcPort = 10000

[test.configCenter.nacos.ClientConfig]
NamespaceId = ""
username = "nacos"
password = "123456"
LogLevel = "debug"

[prod]
