package queue

import "testing"

func TestQueue(t *testing.T) {
	queue:= NewRingQueue(6)
	queue.Enqueue(1)
	queue.Enqueue(2)
	queue.Enqueue(3)
	queue.Enqueue(4)
	queue.Enqueue(5)
	t.Log(queue.LookAll())
	queue.Dequeue()
	queue.Dequeue()
	queue.Dequeue()
	t.Log(queue.LookAll())
	queue.Enqueue(6)
	t.Log(queue.LookAll())
	queue.Enqueue(7)
	t.Log(queue.LookAll())
	queue.Enqueue(8)
	t.Log(queue.LookAll())
	queue.Enqueue(9)
	t.Log(queue.LookAll())
	queue.Enqueue(10)
	t.Log(queue.LookAll())
	queue.Dequeue()
	t.Log(queue.LookAll())
	queue.Dequeue()
	t.Log(queue.LookAll())
	queue.Dequeue()
	t.Log(queue.LookAll())
	queue.Dequeue()
	t.Log(queue.LookAll())
	queue.Dequeue()
	t.Log(queue.LookAll())
	queue.Dequeue()
	t.Log(queue.LookAll())
}
