/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_jni_JNI */

#ifndef _Included_test_jni_JNI
#define _Included_test_jni_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_jni_JNI
 * Method:    testHelloVoid
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test_jni_JNI_testHelloVoid
  (JNIEnv *, jobject);

/*
 * Class:     test_jni_JNI
 * Method:    testHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test_jni_JNI_testHello
  (JNIEnv *, jobject);

/*
 * Class:     test_jni_JNI
 * Method:    fib
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_test_jni_JNI_fib
  (JNIEnv *, jclass, jint);

/*
 * Class:     test_jni_JNI
 * Method:    jnifor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test_jni_JNI_jnifor
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
