// Code generated by protoc-gen-gogo.
// source: response/reply.proto
// DO NOT EDIT!

/*
	Package response is a generated protocol buffer package.

	It is generated from these files:
		response/reply.proto
		response/response.proto

	It has these top-level messages:
		Reply
		Response
*/
package response

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import utils_json "github.com/liov/hoper/go/v2/utils/protobuf"
import _ "github.com/gogo/protobuf/gogoproto"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Reply struct {
	Code uint64                `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data utils_json.StringJson `protobuf:"bytes,2,opt,name=data" json:"data"`
	Msg  string                `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (m *Reply) Reset()                    { *m = Reply{} }
func (m *Reply) String() string            { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()               {}
func (*Reply) Descriptor() ([]byte, []int) { return fileDescriptorReply, []int{0} }

func init() {
	proto.RegisterType((*Reply)(nil), "response.Reply")
}
func (m *Reply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Reply) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Code != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintReply(dAtA, i, uint64(m.Code))
	}
	dAtA[i] = 0x12
	i++
	i = encodeVarintReply(dAtA, i, uint64(m.Data.Size()))
	n1, err := m.Data.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n1
	if len(m.Msg) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintReply(dAtA, i, uint64(len(m.Msg)))
		i += copy(dAtA[i:], m.Msg)
	}
	return i, nil
}

func encodeFixed64Reply(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Reply(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintReply(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Reply) Size() (n int) {
	var l int
	_ = l
	if m.Code != 0 {
		n += 1 + sovReply(uint64(m.Code))
	}
	l = m.Data.Size()
	n += 1 + l + sovReply(uint64(l))
	l = len(m.Msg)
	if l > 0 {
		n += 1 + l + sovReply(uint64(l))
	}
	return n
}

func sovReply(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozReply(x uint64) (n int) {
	return sovReply(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Reply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReply
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Reply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Reply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReply
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReply
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReply
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Data.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReply
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReply
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Msg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipReply(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthReply
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipReply(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowReply
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReply
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReply
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthReply
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowReply
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipReply(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthReply = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowReply   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("response/reply.proto", fileDescriptorReply) }

var fileDescriptorReply = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xb3, 0x36, 0x8a, 0xae, 0x17, 0x59, 0x44, 0x42, 0x85, 0x35, 0x78, 0xca, 0xc5, 0x8c,
	0xb4, 0x6f, 0xd0, 0x9b, 0x1e, 0xe3, 0xcd, 0x8b, 0x34, 0xed, 0xba, 0x5d, 0x49, 0x77, 0x96, 0xdd,
	0x4d, 0xc1, 0x37, 0xcc, 0xb1, 0x4f, 0x20, 0x36, 0x4f, 0x22, 0x99, 0x50, 0xe9, 0xed, 0x9b, 0x9f,
	0x1f, 0xbe, 0xf9, 0xf9, 0xad, 0x57, 0xc1, 0xa1, 0x0d, 0x0a, 0xbc, 0x72, 0xcd, 0x77, 0xe9, 0x3c,
	0x46, 0x14, 0x97, 0xc7, 0x74, 0x7a, 0xdf, 0x46, 0xd3, 0x04, 0xf8, 0x0a, 0x68, 0x21, 0x44, 0x6f,
	0xac, 0x1e, 0x70, 0xac, 0x4d, 0x9f, 0xb4, 0x89, 0x9b, 0xb6, 0x2e, 0x57, 0xb8, 0x05, 0x8d, 0x1a,
	0x81, 0xe2, 0xba, 0xfd, 0xa4, 0x8b, 0x0e, 0xa2, 0xb1, 0xfe, 0xf8, 0xc1, 0xcf, 0xab, 0x41, 0x22,
	0x04, 0x4f, 0x57, 0xb8, 0x56, 0x19, 0xcb, 0x59, 0x91, 0x56, 0xc4, 0xe2, 0x99, 0xa7, 0xeb, 0x65,
	0x5c, 0x66, 0x67, 0x39, 0x2b, 0xae, 0x67, 0x77, 0x25, 0x79, 0x4b, 0x92, 0xbd, 0x91, 0xf7, 0x35,
	0xa0, 0x5d, 0xa4, 0xdd, 0xcf, 0x43, 0x52, 0x51, 0x53, 0xdc, 0xf0, 0xc9, 0x36, 0xe8, 0x6c, 0x92,
	0xb3, 0xe2, 0xaa, 0x1a, 0x70, 0xf1, 0xd2, 0x1d, 0x64, 0xb2, 0x3f, 0xc8, 0xa4, 0xeb, 0x25, 0xdb,
	0xf7, 0x92, 0xfd, 0xf6, 0x92, 0xbd, 0xcf, 0x4f, 0xbe, 0x6c, 0x0c, 0xee, 0x60, 0x83, 0x4e, 0x79,
	0xd0, 0x08, 0xbb, 0x19, 0x8c, 0xf3, 0xfe, 0xff, 0x3e, 0xee, 0xae, 0x2f, 0x28, 0x9a, 0xff, 0x05,
	0x00, 0x00, 0xff, 0xff, 0xcb, 0x9a, 0xf2, 0xdf, 0x20, 0x01, 0x00, 0x00,
}
