# Builder Image
FROM jybl/goprotoc AS source

FROM golang:latest AS upgrade

COPY --from=source /bin/protoc /bin/
COPY --from=source /bin/protoc-gen-enum /bin/
COPY --from=source /bin/protoc-gen-go /bin/
COPY --from=source /bin/protoc-gen-go-grpc /bin/
COPY --from=source /bin/protoc-gen-go-patch /bin/
COPY --from=source /bin/protoc-gen-govalidators /bin/
COPY --from=source /bin/protoc-gen-grpc-gateway /bin/
COPY --from=source /bin/protoc-gen-grpc-gin /bin/
COPY --from=source /bin/protoc-gen-openapiv2 /bin/
COPY --from=source /bin/generate /bin/