FROM golang:latest

ADD ./protoc /bin/
ADD ./protoc-gen-enum /bin/
ADD ./protoc-gen-go /bin/
ADD ./protoc-gen-go-grpc /bin/
ADD ./protoc-gen-go-patch /bin/
ADD ./protoc-gen-govalidators /bin/
ADD ./protoc-gen-grpc-gateway /bin/
ADD ./protoc-gen-grpc-gin /bin/
ADD ./protoc-gen-openapiv2 /bin/
ADD ./generate /bin/
