---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liov.
--- DateTime: 2021/2/8 11:46
---

local metadata_schema = {
    type = "object",
    properties = {
        ikey = {type = "number", minimum = 0},
        skey = {type = "string"},
    },
    required = {"ikey", "skey"},
    additionalProperties = false,
}

local schema = {
    type = "object",
    properties = {
        i = {type = "number", minimum = 0},
        s = {type = "string"},
        t = {type = "array", minItems = 1},
        ip = {type = "string"},
        port = {type = "integer"},
    },
    required = {"i"},
}

local plugin_name = "example-plugin"

local _M = {
    version = 0.1,
    priority = 10000,
    name = plugin_name,
    schema = schema,
    metadata_schema = metadata_schema,
}

function _M.check_schema(conf)
    return core.schema.check(schema, conf)
end