---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liov.
--- DateTime: 2021/2/8 11:46
---

local plugin_name = "example-plugin"

local _M = {
    version = 0.1,
    priority = 10000,
    name = plugin_name,
    schema = schema,
    metadata_schema = metadata_schema,
}