console.log(Object===Object)
console.log(""==="")
console.log(1.0===1)
console.log(NaN===NaN)
console.log(Object==Object)
console.log(""=="")
console.log(1.0==1)
console.log(NaN==NaN)
if ('') console.log(true)
else console.log(false)
