FROM golang:latest

ADD ./protoc /go/bin/
ADD ./protoc-gen-enum /go/bin/
ADD ./protoc-gen-go /go/bin/
ADD ./protoc-gen-gogo /go/bin/
ADD ./protoc-gen-go-grpc /go/bin/
ADD ./protoc-gen-go-patch /go/bin/
ADD ./protoc-gen-govalidators /go/bin/
ADD ./protoc-gen-grpc-gateway /go/bin/
ADD ./protoc-gen-grpc-gin /go/bin/
ADD ./protoc-gen-openapiv2 /go/bin/
